# Generated by Django 3.0.5 on 2020-05-17 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', models.ImageField(upload_to='post_content_image/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Post')),
            ],
        ),
    ]
