# Generated by Django 3.0.5 on 2020-05-17 23:30

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200517_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown', verbose_name='content'),
        ),
    ]
